---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 0m30s
  path: ./apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: staging
  validation: client
